[project]
name = "pandacan"
version = "0.0.10"
requires-python = ">=3.8"
dependencies = [
    "pycryptodome==3.9.8",
    "libusb1",
    "libusb-package",
    "tqdm>=4.14.0",
    "scons",
    "crcmod",
    "numpy==1.17.2",
    "setuptools",
    "requests",
    "nose",
    "parameterized",
    "requests",
    "flake8==3.7.9",
    "cffi==1.11.4",
    "pylint==2.5.2",
    "pre-commit==2.4.0",
    "hexdump>=3.3"
]
